### ISSUE TITLE
Openshift deployment without requiring admin privileges

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#918]
Openshift deployment templates are really great, but could be adapted to run under an unprivileged environment, i.e. shared Openshift cluster where you might not have admin privileges for running Security context changes.

Currently the required workaround is to add `initContainers` + volumes or build images ourselves with permission edits.

**Comment by djuarezg** [comment]
Related to this privileges templates could be improved by separating configuration files to configMaps, as in this extract:

```
volumeMounts:
          (...)
          - mountPath: /etc/faf/plugins/centosmantisbt.conf
            name: centosmantis
            subPath: centosmantisbt.conf
        volumes:
        (...)
        - configMap:
            name: centosmantis
          name: centosmantis
```
